/* tslint:disable */
/* eslint-disable */
/**
 * Workouts API
 *      A comprehensive REST API for managing workout plans, exercises, sets, and users.          ## Features          * **User Management**: Create, retrieve, and delete users     * **Workout Management**: Create, retrieve, and delete workout plans     * **Set Management**: Create, retrieve, and delete exercise sets     * **Exercise Management**: Create, retrieve, and delete exercises     * **AI-Powered Generation**: Generate custom workout plans using OpenAI     * **Weekly Overview**: Get detailed weekly workout schedules for users          ## Collections          The API uses MongoDB with the following collections:     - **users**: User accounts and their associated workout IDs     - **workouts**: Workout plans with day-by-day schedules     - **sets**: Exercise sets with reps, weight, and duration     - **exercises**: Exercise definitions and details     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateExerciseRequest,
  HTTPValidationError,
} from '../models/index';
import {
    CreateExerciseRequestFromJSON,
    CreateExerciseRequestToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface CreateExerciseExercisesPostRequest {
    createExerciseRequest: CreateExerciseRequest;
}

export interface DeleteExerciseExercisesExerciseIdDeleteRequest {
    exerciseId: string;
}

export interface GetAllExercisesExercisesGetRequest {
    skip?: number;
    limit?: number;
}

export interface GetExerciseExercisesExerciseIdGetRequest {
    exerciseId: string;
}

/**
 * 
 */
export class ExercisesApi extends runtime.BaseAPI {

    /**
     * Create a new exercise.  - **exercise_id**: Unique identifier for the exercise - **name**: Name of the exercise - **force**: Force type (optional) - **level**: Difficulty level (optional) - **mechanic**: Mechanic type (optional) - **equipment**: Equipment required (optional) - **primaryMuscles**: Primary muscles targeted (optional) - **secondaryMuscles**: Secondary muscles targeted (optional) - **instructions**: Step-by-step instructions (optional) - **category**: Exercise category (optional)  Returns the created exercise with its ID.
     * Create Exercise
     */
    async createExerciseExercisesPostRaw(requestParameters: CreateExerciseExercisesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['createExerciseRequest'] == null) {
            throw new runtime.RequiredError(
                'createExerciseRequest',
                'Required parameter "createExerciseRequest" was null or undefined when calling createExerciseExercisesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/exercises/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateExerciseRequestToJSON(requestParameters['createExerciseRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Create a new exercise.  - **exercise_id**: Unique identifier for the exercise - **name**: Name of the exercise - **force**: Force type (optional) - **level**: Difficulty level (optional) - **mechanic**: Mechanic type (optional) - **equipment**: Equipment required (optional) - **primaryMuscles**: Primary muscles targeted (optional) - **secondaryMuscles**: Secondary muscles targeted (optional) - **instructions**: Step-by-step instructions (optional) - **category**: Exercise category (optional)  Returns the created exercise with its ID.
     * Create Exercise
     */
    async createExerciseExercisesPost(requestParameters: CreateExerciseExercisesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.createExerciseExercisesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete an exercise by exercise_id.  - **exercise_id**: Unique identifier for the exercise  Returns a confirmation message upon successful deletion.
     * Delete Exercise
     */
    async deleteExerciseExercisesExerciseIdDeleteRaw(requestParameters: DeleteExerciseExercisesExerciseIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['exerciseId'] == null) {
            throw new runtime.RequiredError(
                'exerciseId',
                'Required parameter "exerciseId" was null or undefined when calling deleteExerciseExercisesExerciseIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/exercises/{exercise_id}`;
        urlPath = urlPath.replace(`{${"exercise_id"}}`, encodeURIComponent(String(requestParameters['exerciseId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Delete an exercise by exercise_id.  - **exercise_id**: Unique identifier for the exercise  Returns a confirmation message upon successful deletion.
     * Delete Exercise
     */
    async deleteExerciseExercisesExerciseIdDelete(requestParameters: DeleteExerciseExercisesExerciseIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.deleteExerciseExercisesExerciseIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get all exercises with pagination support.  - **skip**: Number of exercises to skip (for pagination, default: 0) - **limit**: Maximum number of exercises to return (default: 100, max: 1000)  Returns a list of exercises.
     * Get All Exercises
     */
    async getAllExercisesExercisesGetRaw(requestParameters: GetAllExercisesExercisesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<{ [key: string]: any; }>>> {
        const queryParameters: any = {};

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/exercises/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get all exercises with pagination support.  - **skip**: Number of exercises to skip (for pagination, default: 0) - **limit**: Maximum number of exercises to return (default: 100, max: 1000)  Returns a list of exercises.
     * Get All Exercises
     */
    async getAllExercisesExercisesGet(requestParameters: GetAllExercisesExercisesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<{ [key: string]: any; }>> {
        const response = await this.getAllExercisesExercisesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get exercise information by exercise_id.  - **exercise_id**: Unique identifier for the exercise  Returns the exercise data including all fields.
     * Get Exercise
     */
    async getExerciseExercisesExerciseIdGetRaw(requestParameters: GetExerciseExercisesExerciseIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['exerciseId'] == null) {
            throw new runtime.RequiredError(
                'exerciseId',
                'Required parameter "exerciseId" was null or undefined when calling getExerciseExercisesExerciseIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/exercises/{exercise_id}`;
        urlPath = urlPath.replace(`{${"exercise_id"}}`, encodeURIComponent(String(requestParameters['exerciseId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get exercise information by exercise_id.  - **exercise_id**: Unique identifier for the exercise  Returns the exercise data including all fields.
     * Get Exercise
     */
    async getExerciseExercisesExerciseIdGet(requestParameters: GetExerciseExercisesExerciseIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.getExerciseExercisesExerciseIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
