/* tslint:disable */
/* eslint-disable */
/**
 * Workouts API
 *      A comprehensive REST API for managing workout plans, exercises, sets, and users.          ## Features          * **User Management**: Create, retrieve, and delete users     * **Workout Management**: Create, retrieve, and delete workout plans     * **Set Management**: Create, retrieve, and delete exercise sets     * **Exercise Management**: Create, retrieve, and delete exercises     * **AI-Powered Generation**: Generate custom workout plans using OpenAI     * **Weekly Overview**: Get detailed weekly workout schedules for users          ## Collections          The API uses MongoDB with the following collections:     - **users**: User accounts and their associated workout IDs     - **workouts**: Workout plans with day-by-day schedules     - **sets**: Exercise sets with reps, weight, and duration     - **exercises**: Exercise definitions and details     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CompleteSetRequest,
  HTTPValidationError,
  UpdateSetProgressRequest,
} from '../models/index';
import {
    CompleteSetRequestFromJSON,
    CompleteSetRequestToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    UpdateSetProgressRequestFromJSON,
    UpdateSetProgressRequestToJSON,
} from '../models/index';

export interface CompleteSetHistoryUserIdCompletePostRequest {
    userId: string;
    completeSetRequest: CompleteSetRequest;
}

export interface GetLatestHistoryHistoryUserIdLatestGetRequest {
    userId: string;
}

export interface UpdateSetProgressHistoryUserIdUpdatePostRequest {
    userId: string;
    updateSetProgressRequest: UpdateSetProgressRequest;
}

/**
 * 
 */
export class HistoryApi extends runtime.BaseAPI {

    /**
     * Mark a set as complete. When all sets in a day are complete, automatically creates a new history entry for the next day in the workout plan.  - **user_id**: ID of the user - **set_id**: ID of the set to mark as complete  Returns the updated history entry, and indicates if a new day was started.
     * Complete Set
     */
    async completeSetHistoryUserIdCompletePostRaw(requestParameters: CompleteSetHistoryUserIdCompletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling completeSetHistoryUserIdCompletePost().'
            );
        }

        if (requestParameters['completeSetRequest'] == null) {
            throw new runtime.RequiredError(
                'completeSetRequest',
                'Required parameter "completeSetRequest" was null or undefined when calling completeSetHistoryUserIdCompletePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/history/{user_id}/complete`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CompleteSetRequestToJSON(requestParameters['completeSetRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Mark a set as complete. When all sets in a day are complete, automatically creates a new history entry for the next day in the workout plan.  - **user_id**: ID of the user - **set_id**: ID of the set to mark as complete  Returns the updated history entry, and indicates if a new day was started.
     * Complete Set
     */
    async completeSetHistoryUserIdCompletePost(requestParameters: CompleteSetHistoryUserIdCompletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.completeSetHistoryUserIdCompletePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the latest workout history for a user.  - **user_id**: ID of the user  Returns the current day\'s workout progress including all sets and their completion status. If no history exists, creates an initial history entry from the user\'s first workout.
     * Get Latest History
     */
    async getLatestHistoryHistoryUserIdLatestGetRaw(requestParameters: GetLatestHistoryHistoryUserIdLatestGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getLatestHistoryHistoryUserIdLatestGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/history/{user_id}/latest`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get the latest workout history for a user.  - **user_id**: ID of the user  Returns the current day\'s workout progress including all sets and their completion status. If no history exists, creates an initial history entry from the user\'s first workout.
     * Get Latest History
     */
    async getLatestHistoryHistoryUserIdLatestGet(requestParameters: GetLatestHistoryHistoryUserIdLatestGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.getLatestHistoryHistoryUserIdLatestGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Health check endpoint to verify history router is loaded.
     * Health Check
     */
    async healthCheckHistoryHealthGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/history/health`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Health check endpoint to verify history router is loaded.
     * Health Check
     */
    async healthCheckHistoryHealthGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.healthCheckHistoryHealthGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update progress on a specific set (e.g., number of reps completed).  - **user_id**: ID of the user - **set_id**: ID of the set to update - **completed_reps**: Number of reps completed (optional) - **completed_duration_sec**: Duration completed in seconds (optional)  Returns the updated history entry.
     * Update Set Progress
     */
    async updateSetProgressHistoryUserIdUpdatePostRaw(requestParameters: UpdateSetProgressHistoryUserIdUpdatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling updateSetProgressHistoryUserIdUpdatePost().'
            );
        }

        if (requestParameters['updateSetProgressRequest'] == null) {
            throw new runtime.RequiredError(
                'updateSetProgressRequest',
                'Required parameter "updateSetProgressRequest" was null or undefined when calling updateSetProgressHistoryUserIdUpdatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/history/{user_id}/update`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateSetProgressRequestToJSON(requestParameters['updateSetProgressRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Update progress on a specific set (e.g., number of reps completed).  - **user_id**: ID of the user - **set_id**: ID of the set to update - **completed_reps**: Number of reps completed (optional) - **completed_duration_sec**: Duration completed in seconds (optional)  Returns the updated history entry.
     * Update Set Progress
     */
    async updateSetProgressHistoryUserIdUpdatePost(requestParameters: UpdateSetProgressHistoryUserIdUpdatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.updateSetProgressHistoryUserIdUpdatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
