/* tslint:disable */
/* eslint-disable */
/**
 * Workouts API
 *      A comprehensive REST API for managing workout plans, exercises, sets, and users.          ## Features          * **User Management**: Create, retrieve, and delete users     * **Workout Management**: Create, retrieve, and delete workout plans     * **Set Management**: Create, retrieve, and delete exercise sets     * **Exercise Management**: Create, retrieve, and delete exercises     * **AI-Powered Generation**: Generate custom workout plans using OpenAI     * **Weekly Overview**: Get detailed weekly workout schedules for users          ## Collections          The API uses MongoDB with the following collections:     - **users**: User accounts and their associated workout IDs     - **workouts**: Workout plans with day-by-day schedules     - **sets**: Exercise sets with reps, weight, and duration     - **exercises**: Exercise definitions and details     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateSetRequest,
  HTTPValidationError,
} from '../models/index';
import {
    CreateSetRequestFromJSON,
    CreateSetRequestToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface CreateSetSetsPostRequest {
    createSetRequest: CreateSetRequest;
}

export interface DeleteSetSetsSetIdDeleteRequest {
    setId: string;
}

export interface GetSetSetsSetIdGetRequest {
    setId: string;
}

/**
 * 
 */
export class SetsApi extends runtime.BaseAPI {

    /**
     * Create a new set consisting of exercises.  - **name**: Name of the set - **exercise_id**: ID of the exercise this set references - **reps**: Number of repetitions (optional) - **weight**: Weight in kg (optional) - **duration_sec**: Duration in seconds (optional)  Returns the created set with a generated ID.
     * Create Set
     */
    async createSetSetsPostRaw(requestParameters: CreateSetSetsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['createSetRequest'] == null) {
            throw new runtime.RequiredError(
                'createSetRequest',
                'Required parameter "createSetRequest" was null or undefined when calling createSetSetsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/sets/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSetRequestToJSON(requestParameters['createSetRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Create a new set consisting of exercises.  - **name**: Name of the set - **exercise_id**: ID of the exercise this set references - **reps**: Number of repetitions (optional) - **weight**: Weight in kg (optional) - **duration_sec**: Duration in seconds (optional)  Returns the created set with a generated ID.
     * Create Set
     */
    async createSetSetsPost(requestParameters: CreateSetSetsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.createSetSetsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a set by set_id.  - **set_id**: Unique identifier for the set  Returns a confirmation message upon successful deletion.
     * Delete Set
     */
    async deleteSetSetsSetIdDeleteRaw(requestParameters: DeleteSetSetsSetIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['setId'] == null) {
            throw new runtime.RequiredError(
                'setId',
                'Required parameter "setId" was null or undefined when calling deleteSetSetsSetIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/sets/{set_id}`;
        urlPath = urlPath.replace(`{${"set_id"}}`, encodeURIComponent(String(requestParameters['setId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Delete a set by set_id.  - **set_id**: Unique identifier for the set  Returns a confirmation message upon successful deletion.
     * Delete Set
     */
    async deleteSetSetsSetIdDelete(requestParameters: DeleteSetSetsSetIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.deleteSetSetsSetIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get set information by set_id.  - **set_id**: Unique identifier for the set  Returns the set data including name, exercise_id, reps, weight, and duration_sec.
     * Get Set
     */
    async getSetSetsSetIdGetRaw(requestParameters: GetSetSetsSetIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['setId'] == null) {
            throw new runtime.RequiredError(
                'setId',
                'Required parameter "setId" was null or undefined when calling getSetSetsSetIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/sets/{set_id}`;
        urlPath = urlPath.replace(`{${"set_id"}}`, encodeURIComponent(String(requestParameters['setId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get set information by set_id.  - **set_id**: Unique identifier for the set  Returns the set data including name, exercise_id, reps, weight, and duration_sec.
     * Get Set
     */
    async getSetSetsSetIdGet(requestParameters: GetSetSetsSetIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.getSetSetsSetIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
