/* tslint:disable */
/* eslint-disable */
/**
 * Workouts API
 *      A comprehensive REST API for managing workout plans, exercises, sets, and users.          ## Features          * **User Management**: Create, retrieve, and delete users     * **Workout Management**: Create, retrieve, and delete workout plans     * **Set Management**: Create, retrieve, and delete exercise sets     * **Exercise Management**: Create, retrieve, and delete exercises     * **AI-Powered Generation**: Generate custom workout plans using OpenAI     * **Weekly Overview**: Get detailed weekly workout schedules for users          ## Collections          The API uses MongoDB with the following collections:     - **users**: User accounts and their associated workout IDs     - **workouts**: Workout plans with day-by-day schedules     - **sets**: Exercise sets with reps, weight, and duration     - **exercises**: Exercise definitions and details     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GenerateWorkoutRequest,
  HTTPValidationError,
} from '../models/index';
import {
    GenerateWorkoutRequestFromJSON,
    GenerateWorkoutRequestToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface AddWorkoutToUserUsersUserIdWorkoutsWorkoutIdPostRequest {
    userId: string;
    workoutId: string;
}

export interface CreateUserUsersUserIdPostRequest {
    userId: string;
}

export interface DeleteUserUsersUserIdDeleteRequest {
    userId: string;
}

export interface GenerateWorkoutForUserUsersUserIdGenerateWorkoutPostRequest {
    userId: string;
    generateWorkoutRequest: GenerateWorkoutRequest;
}

export interface GetUserUsersUserIdGetRequest {
    userId: string;
}

export interface GetWeeklyOverviewUsersUserIdWeeklyOverviewGetRequest {
    userId: string;
}

export interface RemoveWorkoutFromUserUsersUserIdWorkoutsWorkoutIdDeleteRequest {
    userId: string;
    workoutId: string;
}

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI {

    /**
     * Add a workout ID to the user\'s associated_workout_ids list.  - **user_id**: ID of the user - **workout_id**: ID of the workout to associate with the user  Returns the updated user data.
     * Add Workout To User
     */
    async addWorkoutToUserUsersUserIdWorkoutsWorkoutIdPostRaw(requestParameters: AddWorkoutToUserUsersUserIdWorkoutsWorkoutIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling addWorkoutToUserUsersUserIdWorkoutsWorkoutIdPost().'
            );
        }

        if (requestParameters['workoutId'] == null) {
            throw new runtime.RequiredError(
                'workoutId',
                'Required parameter "workoutId" was null or undefined when calling addWorkoutToUserUsersUserIdWorkoutsWorkoutIdPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users/{user_id}/workouts/{workout_id}`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace(`{${"workout_id"}}`, encodeURIComponent(String(requestParameters['workoutId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Add a workout ID to the user\'s associated_workout_ids list.  - **user_id**: ID of the user - **workout_id**: ID of the workout to associate with the user  Returns the updated user data.
     * Add Workout To User
     */
    async addWorkoutToUserUsersUserIdWorkoutsWorkoutIdPost(requestParameters: AddWorkoutToUserUsersUserIdWorkoutsWorkoutIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.addWorkoutToUserUsersUserIdWorkoutsWorkoutIdPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new user.  - **user_id**: Unique identifier for the user  Returns the created user data with associated_workout_ids set to null by default.
     * Create User
     */
    async createUserUsersUserIdPostRaw(requestParameters: CreateUserUsersUserIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling createUserUsersUserIdPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users/{user_id}`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Create a new user.  - **user_id**: Unique identifier for the user  Returns the created user data with associated_workout_ids set to null by default.
     * Create User
     */
    async createUserUsersUserIdPost(requestParameters: CreateUserUsersUserIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.createUserUsersUserIdPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a user by user_id.  - **user_id**: Unique identifier for the user  Returns a confirmation message upon successful deletion.
     * Delete User
     */
    async deleteUserUsersUserIdDeleteRaw(requestParameters: DeleteUserUsersUserIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling deleteUserUsersUserIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users/{user_id}`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Delete a user by user_id.  - **user_id**: Unique identifier for the user  Returns a confirmation message upon successful deletion.
     * Delete User
     */
    async deleteUserUsersUserIdDelete(requestParameters: DeleteUserUsersUserIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.deleteUserUsersUserIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generate an AI-powered workout plan for an existing user.  - **user_id**: ID of the user (must already exist) - **prompt**: Natural language description of the desired workout - **openai_api_key**: (Optional) OpenAI API key  Returns the created workout with workout_id and summary.
     * Generate Workout For User
     */
    async generateWorkoutForUserUsersUserIdGenerateWorkoutPostRaw(requestParameters: GenerateWorkoutForUserUsersUserIdGenerateWorkoutPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling generateWorkoutForUserUsersUserIdGenerateWorkoutPost().'
            );
        }

        if (requestParameters['generateWorkoutRequest'] == null) {
            throw new runtime.RequiredError(
                'generateWorkoutRequest',
                'Required parameter "generateWorkoutRequest" was null or undefined when calling generateWorkoutForUserUsersUserIdGenerateWorkoutPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/users/{user_id}/generate-workout`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GenerateWorkoutRequestToJSON(requestParameters['generateWorkoutRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Generate an AI-powered workout plan for an existing user.  - **user_id**: ID of the user (must already exist) - **prompt**: Natural language description of the desired workout - **openai_api_key**: (Optional) OpenAI API key  Returns the created workout with workout_id and summary.
     * Generate Workout For User
     */
    async generateWorkoutForUserUsersUserIdGenerateWorkoutPost(requestParameters: GenerateWorkoutForUserUsersUserIdGenerateWorkoutPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.generateWorkoutForUserUsersUserIdGenerateWorkoutPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get user information by user_id.  - **user_id**: Unique identifier for the user  Returns the user data including user_id and associated_workout_ids.
     * Get User
     */
    async getUserUsersUserIdGetRaw(requestParameters: GetUserUsersUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getUserUsersUserIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users/{user_id}`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get user information by user_id.  - **user_id**: Unique identifier for the user  Returns the user data including user_id and associated_workout_ids.
     * Get User
     */
    async getUserUsersUserIdGet(requestParameters: GetUserUsersUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.getUserUsersUserIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get weekly workout overview for a specific user.  - **user_id**: ID of the user  Returns a weekly overview showing all 7 days (Monday-Sunday) for each associated workout.
     * Get Weekly Overview
     */
    async getWeeklyOverviewUsersUserIdWeeklyOverviewGetRaw(requestParameters: GetWeeklyOverviewUsersUserIdWeeklyOverviewGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getWeeklyOverviewUsersUserIdWeeklyOverviewGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users/{user_id}/weekly-overview`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get weekly workout overview for a specific user.  - **user_id**: ID of the user  Returns a weekly overview showing all 7 days (Monday-Sunday) for each associated workout.
     * Get Weekly Overview
     */
    async getWeeklyOverviewUsersUserIdWeeklyOverviewGet(requestParameters: GetWeeklyOverviewUsersUserIdWeeklyOverviewGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.getWeeklyOverviewUsersUserIdWeeklyOverviewGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove a workout ID from the user\'s associated_workout_ids list.  - **user_id**: ID of the user - **workout_id**: ID of the workout to remove from the user\'s associated workouts  Returns the updated user data.
     * Remove Workout From User
     */
    async removeWorkoutFromUserUsersUserIdWorkoutsWorkoutIdDeleteRaw(requestParameters: RemoveWorkoutFromUserUsersUserIdWorkoutsWorkoutIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling removeWorkoutFromUserUsersUserIdWorkoutsWorkoutIdDelete().'
            );
        }

        if (requestParameters['workoutId'] == null) {
            throw new runtime.RequiredError(
                'workoutId',
                'Required parameter "workoutId" was null or undefined when calling removeWorkoutFromUserUsersUserIdWorkoutsWorkoutIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users/{user_id}/workouts/{workout_id}`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));
        urlPath = urlPath.replace(`{${"workout_id"}}`, encodeURIComponent(String(requestParameters['workoutId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Remove a workout ID from the user\'s associated_workout_ids list.  - **user_id**: ID of the user - **workout_id**: ID of the workout to remove from the user\'s associated workouts  Returns the updated user data.
     * Remove Workout From User
     */
    async removeWorkoutFromUserUsersUserIdWorkoutsWorkoutIdDelete(requestParameters: RemoveWorkoutFromUserUsersUserIdWorkoutsWorkoutIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.removeWorkoutFromUserUsersUserIdWorkoutsWorkoutIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
