/* tslint:disable */
/* eslint-disable */
/**
 * Workouts API
 *      A comprehensive REST API for managing workout plans, exercises, sets, and users.          ## Features          * **User Management**: Create, retrieve, and delete users     * **Workout Management**: Create, retrieve, and delete workout plans     * **Set Management**: Create, retrieve, and delete exercise sets     * **Exercise Management**: Create, retrieve, and delete exercises     * **AI-Powered Generation**: Generate custom workout plans using OpenAI     * **Weekly Overview**: Get detailed weekly workout schedules for users          ## Collections          The API uses MongoDB with the following collections:     - **users**: User accounts and their associated workout IDs     - **workouts**: Workout plans with day-by-day schedules     - **sets**: Exercise sets with reps, weight, and duration     - **exercises**: Exercise definitions and details     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateWorkoutRequest,
  HTTPValidationError,
} from '../models/index';
import {
    CreateWorkoutRequestFromJSON,
    CreateWorkoutRequestToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface CreateWorkoutWorkoutsPostRequest {
    createWorkoutRequest: CreateWorkoutRequest;
}

export interface DeleteWorkoutWorkoutsWorkoutIdDeleteRequest {
    workoutId: string;
}

export interface GetWorkoutWorkoutsWorkoutIdGetRequest {
    workoutId: string;
}

/**
 * 
 */
export class WorkoutsApi extends runtime.BaseAPI {

    /**
     * Create a new workout consisting of sets.  - **workout_plan**: Array of day plans, each containing:   - **day**: Day of the week (e.g., \"Monday\", \"Tuesday\")   - **exercises_ids**: Array of set IDs for that day  Returns the created workout with a generated ID.
     * Create Workout
     */
    async createWorkoutWorkoutsPostRaw(requestParameters: CreateWorkoutWorkoutsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['createWorkoutRequest'] == null) {
            throw new runtime.RequiredError(
                'createWorkoutRequest',
                'Required parameter "createWorkoutRequest" was null or undefined when calling createWorkoutWorkoutsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/workouts/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateWorkoutRequestToJSON(requestParameters['createWorkoutRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Create a new workout consisting of sets.  - **workout_plan**: Array of day plans, each containing:   - **day**: Day of the week (e.g., \"Monday\", \"Tuesday\")   - **exercises_ids**: Array of set IDs for that day  Returns the created workout with a generated ID.
     * Create Workout
     */
    async createWorkoutWorkoutsPost(requestParameters: CreateWorkoutWorkoutsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.createWorkoutWorkoutsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a workout by workout_id.  - **workout_id**: Unique identifier for the workout  Returns a confirmation message upon successful deletion.
     * Delete Workout
     */
    async deleteWorkoutWorkoutsWorkoutIdDeleteRaw(requestParameters: DeleteWorkoutWorkoutsWorkoutIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['workoutId'] == null) {
            throw new runtime.RequiredError(
                'workoutId',
                'Required parameter "workoutId" was null or undefined when calling deleteWorkoutWorkoutsWorkoutIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/workouts/{workout_id}`;
        urlPath = urlPath.replace(`{${"workout_id"}}`, encodeURIComponent(String(requestParameters['workoutId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Delete a workout by workout_id.  - **workout_id**: Unique identifier for the workout  Returns a confirmation message upon successful deletion.
     * Delete Workout
     */
    async deleteWorkoutWorkoutsWorkoutIdDelete(requestParameters: DeleteWorkoutWorkoutsWorkoutIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.deleteWorkoutWorkoutsWorkoutIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get workout information by workout_id.  - **workout_id**: Unique identifier for the workout  Returns the workout data including workout_id and workout_plan.
     * Get Workout
     */
    async getWorkoutWorkoutsWorkoutIdGetRaw(requestParameters: GetWorkoutWorkoutsWorkoutIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['workoutId'] == null) {
            throw new runtime.RequiredError(
                'workoutId',
                'Required parameter "workoutId" was null or undefined when calling getWorkoutWorkoutsWorkoutIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/workouts/{workout_id}`;
        urlPath = urlPath.replace(`{${"workout_id"}}`, encodeURIComponent(String(requestParameters['workoutId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get workout information by workout_id.  - **workout_id**: Unique identifier for the workout  Returns the workout data including workout_id and workout_plan.
     * Get Workout
     */
    async getWorkoutWorkoutsWorkoutIdGet(requestParameters: GetWorkoutWorkoutsWorkoutIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.getWorkoutWorkoutsWorkoutIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
