# Run this with `docker-compose up` (or `docker compose up --build` to rebuild)
services:
  db:
    image: mongodb/mongodb-community-server:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3333:3000
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-api
    ports:
      - 8000:8000
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    volumes:
      - ./backend/secrets:/app/secrets

  
