/* tslint:disable */
/* eslint-disable */
/**
 * Workouts API
 *      A comprehensive REST API for managing workout plans, exercises, sets, and users.          ## Features          * **User Management**: Create, retrieve, and delete users     * **Workout Management**: Create, retrieve, and delete workout plans     * **Set Management**: Create, retrieve, and delete exercise sets     * **Exercise Management**: Create, retrieve, and delete exercises     * **AI-Powered Generation**: Generate custom workout plans using OpenAI     * **Weekly Overview**: Get detailed weekly workout schedules for users          ## Collections          The API uses MongoDB with the following collections:     - **users**: User accounts and their associated workout IDs     - **workouts**: Workout plans with day-by-day schedules     - **sets**: Exercise sets with reps, weight, and duration     - **exercises**: Exercise definitions and details     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request model for marking a set as complete.
 * @export
 * @interface CompleteSetRequest
 */
export interface CompleteSetRequest {
    /**
     * ID of the set to mark complete
     * @type {string}
     * @memberof CompleteSetRequest
     */
    setId: string;
}

/**
 * Check if a given object implements the CompleteSetRequest interface.
 */
export function instanceOfCompleteSetRequest(value: object): value is CompleteSetRequest {
    if (!('setId' in value) || value['setId'] === undefined) return false;
    return true;
}

export function CompleteSetRequestFromJSON(json: any): CompleteSetRequest {
    return CompleteSetRequestFromJSONTyped(json, false);
}

export function CompleteSetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompleteSetRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'setId': json['set_id'],
    };
}

export function CompleteSetRequestToJSON(json: any): CompleteSetRequest {
    return CompleteSetRequestToJSONTyped(json, false);
}

export function CompleteSetRequestToJSONTyped(value?: CompleteSetRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'set_id': value['setId'],
    };
}

