/* tslint:disable */
/* eslint-disable */
/**
 * Workouts API
 *      A comprehensive REST API for managing workout plans, exercises, sets, and users.          ## Features          * **User Management**: Create, retrieve, and delete users     * **Workout Management**: Create, retrieve, and delete workout plans     * **Set Management**: Create, retrieve, and delete exercise sets     * **Exercise Management**: Create, retrieve, and delete exercises     * **AI-Powered Generation**: Generate custom workout plans using OpenAI     * **Weekly Overview**: Get detailed weekly workout schedules for users          ## Collections          The API uses MongoDB with the following collections:     - **users**: User accounts and their associated workout IDs     - **workouts**: Workout plans with day-by-day schedules     - **sets**: Exercise sets with reps, weight, and duration     - **exercises**: Exercise definitions and details     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request model for creating an exercise.
 * @export
 * @interface CreateExerciseRequest
 */
export interface CreateExerciseRequest {
    /**
     * Unique identifier for the exercise
     * @type {string}
     * @memberof CreateExerciseRequest
     */
    exerciseId: string;
    /**
     * Name of the exercise
     * @type {string}
     * @memberof CreateExerciseRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateExerciseRequest
     */
    force?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateExerciseRequest
     */
    level?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateExerciseRequest
     */
    mechanic?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateExerciseRequest
     */
    equipment?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateExerciseRequest
     */
    primaryMuscles?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateExerciseRequest
     */
    secondaryMuscles?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateExerciseRequest
     */
    instructions?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof CreateExerciseRequest
     */
    category?: string | null;
}

/**
 * Check if a given object implements the CreateExerciseRequest interface.
 */
export function instanceOfCreateExerciseRequest(value: object): value is CreateExerciseRequest {
    if (!('exerciseId' in value) || value['exerciseId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateExerciseRequestFromJSON(json: any): CreateExerciseRequest {
    return CreateExerciseRequestFromJSONTyped(json, false);
}

export function CreateExerciseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateExerciseRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'exerciseId': json['exercise_id'],
        'name': json['name'],
        'force': json['force'] == null ? undefined : json['force'],
        'level': json['level'] == null ? undefined : json['level'],
        'mechanic': json['mechanic'] == null ? undefined : json['mechanic'],
        'equipment': json['equipment'] == null ? undefined : json['equipment'],
        'primaryMuscles': json['primaryMuscles'] == null ? undefined : json['primaryMuscles'],
        'secondaryMuscles': json['secondaryMuscles'] == null ? undefined : json['secondaryMuscles'],
        'instructions': json['instructions'] == null ? undefined : json['instructions'],
        'category': json['category'] == null ? undefined : json['category'],
    };
}

export function CreateExerciseRequestToJSON(json: any): CreateExerciseRequest {
    return CreateExerciseRequestToJSONTyped(json, false);
}

export function CreateExerciseRequestToJSONTyped(value?: CreateExerciseRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'exercise_id': value['exerciseId'],
        'name': value['name'],
        'force': value['force'],
        'level': value['level'],
        'mechanic': value['mechanic'],
        'equipment': value['equipment'],
        'primaryMuscles': value['primaryMuscles'],
        'secondaryMuscles': value['secondaryMuscles'],
        'instructions': value['instructions'],
        'category': value['category'],
    };
}

