/* tslint:disable */
/* eslint-disable */
/**
 * Workouts API
 *      A comprehensive REST API for managing workout plans, exercises, sets, and users.          ## Features          * **User Management**: Create, retrieve, and delete users     * **Workout Management**: Create, retrieve, and delete workout plans     * **Set Management**: Create, retrieve, and delete exercise sets     * **Exercise Management**: Create, retrieve, and delete exercises     * **AI-Powered Generation**: Generate custom workout plans using OpenAI     * **Weekly Overview**: Get detailed weekly workout schedules for users          ## Collections          The API uses MongoDB with the following collections:     - **users**: User accounts and their associated workout IDs     - **workouts**: Workout plans with day-by-day schedules     - **sets**: Exercise sets with reps, weight, and duration     - **exercises**: Exercise definitions and details     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request model for creating an exercise set.
 * @export
 * @interface CreateSetRequest
 */
export interface CreateSetRequest {
    /**
     * Name of the set
     * @type {string}
     * @memberof CreateSetRequest
     */
    name: string;
    /**
     * ID of the exercise this set references
     * @type {string}
     * @memberof CreateSetRequest
     */
    exerciseId: string;
    /**
     * 
     * @type {number}
     * @memberof CreateSetRequest
     */
    reps?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CreateSetRequest
     */
    weight?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CreateSetRequest
     */
    durationSec?: number | null;
}

/**
 * Check if a given object implements the CreateSetRequest interface.
 */
export function instanceOfCreateSetRequest(value: object): value is CreateSetRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('exerciseId' in value) || value['exerciseId'] === undefined) return false;
    return true;
}

export function CreateSetRequestFromJSON(json: any): CreateSetRequest {
    return CreateSetRequestFromJSONTyped(json, false);
}

export function CreateSetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSetRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'exerciseId': json['exercise_id'],
        'reps': json['reps'] == null ? undefined : json['reps'],
        'weight': json['weight'] == null ? undefined : json['weight'],
        'durationSec': json['duration_sec'] == null ? undefined : json['duration_sec'],
    };
}

export function CreateSetRequestToJSON(json: any): CreateSetRequest {
    return CreateSetRequestToJSONTyped(json, false);
}

export function CreateSetRequestToJSONTyped(value?: CreateSetRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'exercise_id': value['exerciseId'],
        'reps': value['reps'],
        'weight': value['weight'],
        'duration_sec': value['durationSec'],
    };
}

