/* tslint:disable */
/* eslint-disable */
/**
 * Workouts API
 *      A comprehensive REST API for managing workout plans, exercises, sets, and users.          ## Features          * **User Management**: Create, retrieve, and delete users     * **Workout Management**: Create, retrieve, and delete workout plans     * **Set Management**: Create, retrieve, and delete exercise sets     * **Exercise Management**: Create, retrieve, and delete exercises     * **AI-Powered Generation**: Generate custom workout plans using OpenAI     * **Weekly Overview**: Get detailed weekly workout schedules for users          ## Collections          The API uses MongoDB with the following collections:     - **users**: User accounts and their associated workout IDs     - **workouts**: Workout plans with day-by-day schedules     - **sets**: Exercise sets with reps, weight, and duration     - **exercises**: Exercise definitions and details     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DayPlan } from './DayPlan';
import {
    DayPlanFromJSON,
    DayPlanFromJSONTyped,
    DayPlanToJSON,
    DayPlanToJSONTyped,
} from './DayPlan';

/**
 * Request model for creating a workout plan.
 * @export
 * @interface CreateWorkoutRequest
 */
export interface CreateWorkoutRequest {
    /**
     * Array of day plans, each with day and exercises_ids
     * @type {Array<DayPlan>}
     * @memberof CreateWorkoutRequest
     */
    workoutPlan: Array<DayPlan>;
}

/**
 * Check if a given object implements the CreateWorkoutRequest interface.
 */
export function instanceOfCreateWorkoutRequest(value: object): value is CreateWorkoutRequest {
    if (!('workoutPlan' in value) || value['workoutPlan'] === undefined) return false;
    return true;
}

export function CreateWorkoutRequestFromJSON(json: any): CreateWorkoutRequest {
    return CreateWorkoutRequestFromJSONTyped(json, false);
}

export function CreateWorkoutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWorkoutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'workoutPlan': ((json['workout_plan'] as Array<any>).map(DayPlanFromJSON)),
    };
}

export function CreateWorkoutRequestToJSON(json: any): CreateWorkoutRequest {
    return CreateWorkoutRequestToJSONTyped(json, false);
}

export function CreateWorkoutRequestToJSONTyped(value?: CreateWorkoutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'workout_plan': ((value['workoutPlan'] as Array<any>).map(DayPlanToJSON)),
    };
}

