/* tslint:disable */
/* eslint-disable */
/**
 * Workouts API
 *      A comprehensive REST API for managing workout plans, exercises, sets, and users.          ## Features          * **User Management**: Create, retrieve, and delete users     * **Workout Management**: Create, retrieve, and delete workout plans     * **Set Management**: Create, retrieve, and delete exercise sets     * **Exercise Management**: Create, retrieve, and delete exercises     * **AI-Powered Generation**: Generate custom workout plans using OpenAI     * **Weekly Overview**: Get detailed weekly workout schedules for users          ## Collections          The API uses MongoDB with the following collections:     - **users**: User accounts and their associated workout IDs     - **workouts**: Workout plans with day-by-day schedules     - **sets**: Exercise sets with reps, weight, and duration     - **exercises**: Exercise definitions and details     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Day plan model for workout schedules.
 * @export
 * @interface DayPlan
 */
export interface DayPlan {
    /**
     * Day of the week
     * @type {string}
     * @memberof DayPlan
     */
    day: string;
    /**
     * List of set IDs for this day
     * @type {Array<string>}
     * @memberof DayPlan
     */
    exercisesIds: Array<string>;
}

/**
 * Check if a given object implements the DayPlan interface.
 */
export function instanceOfDayPlan(value: object): value is DayPlan {
    if (!('day' in value) || value['day'] === undefined) return false;
    if (!('exercisesIds' in value) || value['exercisesIds'] === undefined) return false;
    return true;
}

export function DayPlanFromJSON(json: any): DayPlan {
    return DayPlanFromJSONTyped(json, false);
}

export function DayPlanFromJSONTyped(json: any, ignoreDiscriminator: boolean): DayPlan {
    if (json == null) {
        return json;
    }
    return {
        
        'day': json['day'],
        'exercisesIds': json['exercises_ids'],
    };
}

export function DayPlanToJSON(json: any): DayPlan {
    return DayPlanToJSONTyped(json, false);
}

export function DayPlanToJSONTyped(value?: DayPlan | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'day': value['day'],
        'exercises_ids': value['exercisesIds'],
    };
}

