/* tslint:disable */
/* eslint-disable */
/**
 * Workouts API
 *      A comprehensive REST API for managing workout plans, exercises, sets, and users.          ## Features          * **User Management**: Create, retrieve, and delete users     * **Workout Management**: Create, retrieve, and delete workout plans     * **Set Management**: Create, retrieve, and delete exercise sets     * **Exercise Management**: Create, retrieve, and delete exercises     * **AI-Powered Generation**: Generate custom workout plans using OpenAI     * **Weekly Overview**: Get detailed weekly workout schedules for users          ## Collections          The API uses MongoDB with the following collections:     - **users**: User accounts and their associated workout IDs     - **workouts**: Workout plans with day-by-day schedules     - **sets**: Exercise sets with reps, weight, and duration     - **exercises**: Exercise definitions and details     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request model for AI-powered workout generation.
 * @export
 * @interface GenerateWorkoutRequest
 */
export interface GenerateWorkoutRequest {
    /**
     * Natural language description of the desired workout
     * @type {string}
     * @memberof GenerateWorkoutRequest
     */
    prompt: string;
    /**
     * 
     * @type {string}
     * @memberof GenerateWorkoutRequest
     */
    openaiApiKey?: string | null;
}

/**
 * Check if a given object implements the GenerateWorkoutRequest interface.
 */
export function instanceOfGenerateWorkoutRequest(value: object): value is GenerateWorkoutRequest {
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    return true;
}

export function GenerateWorkoutRequestFromJSON(json: any): GenerateWorkoutRequest {
    return GenerateWorkoutRequestFromJSONTyped(json, false);
}

export function GenerateWorkoutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateWorkoutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'prompt': json['prompt'],
        'openaiApiKey': json['openai_api_key'] == null ? undefined : json['openai_api_key'],
    };
}

export function GenerateWorkoutRequestToJSON(json: any): GenerateWorkoutRequest {
    return GenerateWorkoutRequestToJSONTyped(json, false);
}

export function GenerateWorkoutRequestToJSONTyped(value?: GenerateWorkoutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prompt': value['prompt'],
        'openai_api_key': value['openaiApiKey'],
    };
}

