/* tslint:disable */
/* eslint-disable */
/**
 * Workouts API
 *      A comprehensive REST API for managing workout plans, exercises, sets, and users.          ## Features          * **User Management**: Create, retrieve, and delete users     * **Workout Management**: Create, retrieve, and delete workout plans     * **Set Management**: Create, retrieve, and delete exercise sets     * **Exercise Management**: Create, retrieve, and delete exercises     * **AI-Powered Generation**: Generate custom workout plans using OpenAI     * **Weekly Overview**: Get detailed weekly workout schedules for users          ## Collections          The API uses MongoDB with the following collections:     - **users**: User accounts and their associated workout IDs     - **workouts**: Workout plans with day-by-day schedules     - **sets**: Exercise sets with reps, weight, and duration     - **exercises**: Exercise definitions and details     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ValidationError } from './ValidationError';
import {
    ValidationErrorFromJSON,
    ValidationErrorFromJSONTyped,
    ValidationErrorToJSON,
    ValidationErrorToJSONTyped,
} from './ValidationError';

/**
 * 
 * @export
 * @interface HTTPValidationError
 */
export interface HTTPValidationError {
    /**
     * 
     * @type {Array<ValidationError>}
     * @memberof HTTPValidationError
     */
    detail?: Array<ValidationError>;
}

/**
 * Check if a given object implements the HTTPValidationError interface.
 */
export function instanceOfHTTPValidationError(value: object): value is HTTPValidationError {
    return true;
}

export function HTTPValidationErrorFromJSON(json: any): HTTPValidationError {
    return HTTPValidationErrorFromJSONTyped(json, false);
}

export function HTTPValidationErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): HTTPValidationError {
    if (json == null) {
        return json;
    }
    return {
        
        'detail': json['detail'] == null ? undefined : ((json['detail'] as Array<any>).map(ValidationErrorFromJSON)),
    };
}

export function HTTPValidationErrorToJSON(json: any): HTTPValidationError {
    return HTTPValidationErrorToJSONTyped(json, false);
}

export function HTTPValidationErrorToJSONTyped(value?: HTTPValidationError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'detail': value['detail'] == null ? undefined : ((value['detail'] as Array<any>).map(ValidationErrorToJSON)),
    };
}

