/* tslint:disable */
/* eslint-disable */
/**
 * Workouts API
 *      A comprehensive REST API for managing workout plans, exercises, sets, and users.          ## Features          * **User Management**: Create, retrieve, and delete users     * **Workout Management**: Create, retrieve, and delete workout plans     * **Set Management**: Create, retrieve, and delete exercise sets     * **Exercise Management**: Create, retrieve, and delete exercises     * **AI-Powered Generation**: Generate custom workout plans using OpenAI     * **Weekly Overview**: Get detailed weekly workout schedules for users          ## Collections          The API uses MongoDB with the following collections:     - **users**: User accounts and their associated workout IDs     - **workouts**: Workout plans with day-by-day schedules     - **sets**: Exercise sets with reps, weight, and duration     - **exercises**: Exercise definitions and details     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request model for updating progress on sets.
 * @export
 * @interface UpdateSetProgressRequest
 */
export interface UpdateSetProgressRequest {
    /**
     * ID of the set to update
     * @type {string}
     * @memberof UpdateSetProgressRequest
     */
    setId: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateSetProgressRequest
     */
    completedReps?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateSetProgressRequest
     */
    completedDurationSec?: number | null;
}

/**
 * Check if a given object implements the UpdateSetProgressRequest interface.
 */
export function instanceOfUpdateSetProgressRequest(value: object): value is UpdateSetProgressRequest {
    if (!('setId' in value) || value['setId'] === undefined) return false;
    return true;
}

export function UpdateSetProgressRequestFromJSON(json: any): UpdateSetProgressRequest {
    return UpdateSetProgressRequestFromJSONTyped(json, false);
}

export function UpdateSetProgressRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSetProgressRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'setId': json['set_id'],
        'completedReps': json['completed_reps'] == null ? undefined : json['completed_reps'],
        'completedDurationSec': json['completed_duration_sec'] == null ? undefined : json['completed_duration_sec'],
    };
}

export function UpdateSetProgressRequestToJSON(json: any): UpdateSetProgressRequest {
    return UpdateSetProgressRequestToJSONTyped(json, false);
}

export function UpdateSetProgressRequestToJSONTyped(value?: UpdateSetProgressRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'set_id': value['setId'],
        'completed_reps': value['completedReps'],
        'completed_duration_sec': value['completedDurationSec'],
    };
}

